from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    target = Path(path)
    text = target.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"expected block not found in {path}")
    if text.count(old) != 1:
        raise SystemExit(f"expected exactly one block in {path}, found {text.count(old)}")
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


# ESP32 UART: a pending JOB that may already have reached Arduino is converted
# into a reliable JOB_CANCEL handshake instead of becoming impossible to clear.
replace_once(
    "firmware/esp32/src/CM_UartEventReceiver.cpp",
    '''bool UartEventReceiver::cancelPendingJob(const char* detail)\n{\n    if (!m_hasPendingJob || m_hasJobDelivery || m_waitingJobAck ||\n        m_jobSendAttempts != 0U || m_hasPendingCancel || m_hasJobCancel ||\n        !isValidJobAckDetail(detail))\n        return false;\n\n    publishJobDelivery(JobDeliveryResult::Cancelled,\n                       m_pendingJob.jobId,\n                       0U,\n                       detail != nullptr ? detail : "CANCELLED");\n    m_pendingJob = OutgoingWindingJob();\n    m_hasPendingJob = false;\n    m_waitingJobAck = false;\n    m_lastJobSendMs = 0UL;\n    m_jobSendAttempts = 0U;\n    return true;\n}\n''',
    '''bool UartEventReceiver::cancelPendingJob(const char* detail)\n{\n    if (!m_hasPendingJob || m_hasJobDelivery || m_hasPendingCancel ||\n        m_hasJobCancel || !isValidJobAckDetail(detail))\n        return false;\n\n    const uint32_t jobId = m_pendingJob.jobId;\n    const uint8_t sendAttempts = m_jobSendAttempts;\n    const bool mayHaveReachedArduino = m_waitingJobAck || sendAttempts != 0U;\n\n    // Stop JOB retransmission first. If even one frame may have reached Arduino,\n    // do not declare a local-only cancellation: switch to an idempotent remote\n    // JOB_CANCEL handshake so a lost JOB_ACK can never leave a ghost job behind.\n    m_pendingJob = OutgoingWindingJob();\n    m_hasPendingJob = false;\n    m_waitingJobAck = false;\n    m_lastJobSendMs = 0UL;\n    m_jobSendAttempts = 0U;\n\n    if (!mayHaveReachedArduino)\n    {\n        publishJobDelivery(JobDeliveryResult::Cancelled,\n                           jobId,\n                           0U,\n                           detail != nullptr ? detail : "CANCELLED");\n        return true;\n    }\n\n    m_cancelJobId = jobId;\n    m_hasPendingCancel = true;\n    m_lastCancelSendMs = 0UL;\n    m_cancelSendAttempts = 0U;\n    return true;\n}\n''')

replace_once(
    "firmware/esp32/src/CM_UartEventReceiver.h",
    '''    bool requestJobCancel(uint32_t jobId);\n    bool takeJobCancel(JobCancelEvent& event);\n    bool jobCancelPending() const;\n\n    void sendAck(uint32_t runId, const char* status);\n''',
    '''    bool requestJobCancel(uint32_t jobId);\n    bool takeJobCancel(JobCancelEvent& event);\n    bool jobCancelPending() const;\n    void rememberJobId(uint32_t jobId);\n\n    void sendAck(uint32_t runId, const char* status);\n''')

replace_once(
    "firmware/esp32/src/CM_UartEventReceiver.cpp",
    '''bool UartEventReceiver::jobCancelPending() const\n{\n    return m_hasPendingCancel;\n}\n\nvoid UartEventReceiver::sendAck(uint32_t runId, const char* status)\n''',
    '''bool UartEventReceiver::jobCancelPending() const\n{\n    return m_hasPendingCancel;\n}\n\nvoid UartEventReceiver::rememberJobId(uint32_t jobId)\n{\n    if (jobId == 0UL) return;\n    if (!m_hasLastQueuedJobId || jobId > m_lastQueuedJobId)\n    {\n        m_lastQueuedJobId = jobId;\n        m_hasLastQueuedJobId = true;\n    }\n}\n\nvoid UartEventReceiver::sendAck(uint32_t runId, const char* status)\n''')

replace_once(
    "firmware/esp32/src/CM_UartEventReceiver.cpp",
    '''bool UartEventReceiver::processCancelAck(char* line)\n{\n    if (!validateAndStripJobReplyCrc(line)) return false;\n\n    char* save = nullptr;\n    char* version = strtok_r(line, "|", &save);\n    char* category = strtok_r(nullptr, "|", &save);\n    char* jobText = strtok_r(nullptr, "|", &save);\n    char* status = strtok_r(nullptr, "|", &save);\n    char* detail = strtok_r(nullptr, "|", &save);\n    char* capability = strtok_r(nullptr, "|", &save);\n    char* extra = strtok_r(nullptr, "|", &save);\n    if (version == nullptr || category == nullptr || jobText == nullptr ||\n        status == nullptr || extra != nullptr || strcmp(version, "CMP1") != 0 ||\n        strcmp(category, "JOB_CANCEL_ACK") != 0 || !m_hasPendingCancel ||\n        !isValidJobAckDetail(detail) ||\n        (capability != nullptr && strcmp(capability, "C") != 0))\n        return false;\n\n    uint32_t jobId = 0UL;\n    if (!parseDecimal32(jobText, jobId) || jobId != m_cancelJobId)\n        return false;\n\n    JobCancelResult result = JobCancelResult::None;\n    if (strcmp(status, "CANCELLED") == 0)\n        result = JobCancelResult::Cancelled;\n    else if (strcmp(status, "REJECTED") == 0)\n    {\n        if (detail == nullptr) return false;\n        result = JobCancelResult::Rejected;\n    }\n    else\n        return false;\n\n    publishJobCancel(result,\n                     jobId,\n                     m_cancelSendAttempts,\n                     detail != nullptr ? detail :\n                     (result == JobCancelResult::Cancelled ? "CANCELLED" : "REJECTED"));\n    m_hasPendingCancel = false;\n    m_cancelJobId = 0UL;\n    m_cancelSendAttempts = 0U;\n    return true;\n}\n''',
    '''bool UartEventReceiver::processCancelAck(char* line)\n{\n    if (!validateAndStripJobReplyCrc(line)) return false;\n\n    char* save = nullptr;\n    char* version = strtok_r(line, "|", &save);\n    char* category = strtok_r(nullptr, "|", &save);\n    char* jobText = strtok_r(nullptr, "|", &save);\n    char* status = strtok_r(nullptr, "|", &save);\n    char* detail = strtok_r(nullptr, "|", &save);\n    char* capability = strtok_r(nullptr, "|", &save);\n    char* extra = strtok_r(nullptr, "|", &save);\n    if (version == nullptr || category == nullptr || jobText == nullptr ||\n        status == nullptr || extra != nullptr || strcmp(version, "CMP1") != 0 ||\n        strcmp(category, "JOB_CANCEL_ACK") != 0 ||\n        !isValidJobAckDetail(detail) ||\n        (capability != nullptr && strcmp(capability, "C") != 0))\n        return false;\n\n    uint32_t jobId = 0UL;\n    if (!parseDecimal32(jobText, jobId)) return false;\n\n    // Physical Arduino fallback: D * # D sends a CRC-protected ALL_CLEAR with\n    // job_id=0 after Arduino has proved that no ESP32 job is physically active.\n    // Correlate it to the currently pending/recovered ESP32 job and publish the\n    // normal cancellation event so persistence follows the same audited path.\n    if (jobId == 0UL)\n    {\n        if (strcmp(status, "CANCELLED") != 0 || detail == nullptr ||\n            strcmp(detail, "ALL_CLEAR") != 0 || !m_hasLastQueuedJobId)\n            return false;\n\n        const uint32_t clearedJobId = m_hasPendingCancel\n            ? m_cancelJobId\n            : (m_hasPendingJob ? m_pendingJob.jobId : m_lastQueuedJobId);\n        if (clearedJobId == 0UL) return false;\n\n        m_pendingJob = OutgoingWindingJob();\n        m_hasPendingJob = false;\n        m_waitingJobAck = false;\n        m_lastJobSendMs = 0UL;\n        m_jobSendAttempts = 0U;\n        m_hasPendingCancel = false;\n        m_cancelJobId = 0UL;\n        m_lastCancelSendMs = 0UL;\n        m_cancelSendAttempts = 0U;\n        publishJobCancel(JobCancelResult::Cancelled,\n                         clearedJobId,\n                         0U,\n                         "ALL_CLEAR");\n        return true;\n    }\n\n    if (!m_hasPendingCancel || jobId != m_cancelJobId) return false;\n\n    JobCancelResult result = JobCancelResult::None;\n    if (strcmp(status, "CANCELLED") == 0)\n        result = JobCancelResult::Cancelled;\n    else if (strcmp(status, "REJECTED") == 0)\n    {\n        if (detail == nullptr) return false;\n        result = JobCancelResult::Rejected;\n    }\n    else\n        return false;\n\n    publishJobCancel(result,\n                     jobId,\n                     m_cancelSendAttempts,\n                     detail != nullptr ? detail :\n                     (result == JobCancelResult::Cancelled ? "CANCELLED" : "REJECTED"));\n    m_hasPendingCancel = false;\n    m_cancelJobId = 0UL;\n    m_cancelSendAttempts = 0U;\n    return true;\n}\n''')

# Persisted cancellation is safe for every no-run delivery state once Arduino
# has positively confirmed that the physical remote job is absent.
Path("firmware/esp32/src/CM_JobStateRemoteCancel.cpp").write_text('''#include "CM_JobStateStore.h"\n\nnamespace CM\n{\nbool JobStateStore::closeAfterRemoteCancel(uint32_t sessionId, uint32_t nowMs)\n{\n    JobRuntimeState state;\n    if (!load(sessionId, state)) return false;\n\n    if (state.deliveryState == JobDeliveryState::Cancelled &&\n        state.executionState == JobExecutionState::ClosedAfterReview)\n    {\n        return true;\n    }\n\n    // A positive Arduino CANCELLED/ALL_CLEAR acknowledgement proves only that\n    // no remote job remains on the physical controller. It never proves a run\n    // completed. Permit closure only while there is zero physical-run evidence.\n    const bool waitingOnly =\n        state.executionState == JobExecutionState::WaitingDelivery ||\n        state.executionState == JobExecutionState::WaitingPhysicalStart;\n    if (!waitingOnly || state.lastRunId != 0UL || state.completedRuns != 0U)\n        return false;\n\n    state.deliveryState = JobDeliveryState::Cancelled;\n    state.executionState = JobExecutionState::ClosedAfterReview;\n    state.updatedUptimeMs = nowMs;\n    return writeAtomic(state);\n}\n}\n''', encoding="utf-8")

replace_once(
    "firmware/esp32/src/CM_JobStateStore.h",
    '''    // Persists a cancellation only after Arduino has positively confirmed that\n    // the accepted job was still waiting for physical START and was discarded.\n    bool closeAfterRemoteCancel(uint32_t sessionId, uint32_t nowMs);\n''',
    '''    // Persists a cancellation only after Arduino has positively confirmed that\n    // no remote job remains. This is valid only before any physical-run evidence.\n    bool closeAfterRemoteCancel(uint32_t sessionId, uint32_t nowMs);\n''')

# Web cancel: allow an operator to cancel while JOB_ACK is still pending. The
# transport decides whether this is a local-only cancel or requires JOB_CANCEL.
replace_once(
    "firmware/esp32/src/main.cpp",
    '''    if (runActive || completedRuns != 0U || lastRunId != 0UL || jobAwaitingAck ||\n        lastJobResult != CM::JobDeliveryResult::Accepted)\n    {\n        webServer.send(409, "application/json", "{\\"error\\":\\"job_not_waiting_physical_start\\"}");\n        return;\n    }\n''',
    '''    if (runActive || completedRuns != 0U || lastRunId != 0UL)\n    {\n        webServer.send(409, "application/json", "{\\"error\\":\\"job_has_physical_run_evidence\\"}");\n        return;\n    }\n''')

replace_once(
    "firmware/esp32/src/main.cpp",
    '''    if (persisted.jobId != jobId ||\n        persisted.deliveryState != CM::JobDeliveryState::Accepted ||\n        persisted.executionState != CM::JobExecutionState::WaitingPhysicalStart ||\n        persisted.lastRunId != 0UL || persisted.completedRuns != 0U)\n    {\n        webServer.send(409, "application/json", "{\\"error\\":\\"persisted_job_not_cancellable\\"}");\n        return;\n    }\n\n    if (!receiver.requestJobCancel(jobId))\n    {\n        webServer.send(409, "application/json", "{\\"error\\":\\"uart_cancel_sender_busy\\"}");\n        return;\n    }\n\n    jobCancelAwaitingAck = true;\n    recoveryInfo.mayCreateNewJob = false;\n''',
    '''    const bool pendingDelivery =\n        (persisted.deliveryState == CM::JobDeliveryState::Created ||\n         persisted.deliveryState == CM::JobDeliveryState::Delivering) &&\n        persisted.executionState == CM::JobExecutionState::WaitingDelivery;\n    const bool acceptedReady =\n        persisted.deliveryState == CM::JobDeliveryState::Accepted &&\n        persisted.executionState == CM::JobExecutionState::WaitingPhysicalStart;\n    if (persisted.jobId != jobId || (!pendingDelivery && !acceptedReady) ||\n        persisted.lastRunId != 0UL || persisted.completedRuns != 0U)\n    {\n        webServer.send(409, "application/json", "{\\"error\\":\\"persisted_job_not_cancellable\\"}");\n        return;\n    }\n\n    const bool queued = pendingDelivery\n        ? receiver.cancelPendingJob("OPERATOR_CANCEL")\n        : receiver.requestJobCancel(jobId);\n    if (!queued)\n    {\n        webServer.send(409, "application/json", "{\\"error\\":\\"uart_cancel_sender_busy\\"}");\n        return;\n    }\n\n    jobAwaitingAck = false;\n    jobCancelAwaitingAck = receiver.jobCancelPending();\n    recoveryInfo.mayCreateNewJob = false;\n''')

replace_once(
    "firmware/esp32/src/main.cpp",
    '''    activeJobId = recoveryInfo.state.jobId;\n    activeSessionId = recoveryInfo.state.sessionId;\n''',
    '''    activeJobId = recoveryInfo.state.jobId;\n    activeSessionId = recoveryInfo.state.sessionId;\n    receiver.rememberJobId(activeJobId);\n''')

# Arduino emits a CRC-protected global clear proof from the physical keypad.
replace_once(
    "Arduino/CM_UartEventTransport.h",
    '''    bool takeRemoteCancel(uint32_t& jobId);\n    void sendJobCancelResult(uint32_t jobId, bool cancelled, const char* reason);\n\n    uint8_t queuedCount() const;\n''',
    '''    bool takeRemoteCancel(uint32_t& jobId);\n    void sendJobCancelResult(uint32_t jobId, bool cancelled, const char* reason);\n    void sendJobClear();\n\n    uint8_t queuedCount() const;\n''')

replace_once(
    "Arduino/CM_UartEventTransport.cpp",
    '''void UartEventTransport::sendJobCancelResult(uint32_t jobId,\n                                             bool cancelled,\n                                             const char* reason)\n{\n    writeJobReply(true, jobId, cancelled, reason);\n}\n\nvoid UartEventTransport::writeJobReply(bool cancelReply,\n''',
    '''void UartEventTransport::sendJobCancelResult(uint32_t jobId,\n                                             bool cancelled,\n                                             const char* reason)\n{\n    writeJobReply(true, jobId, cancelled, reason);\n}\n\nvoid UartEventTransport::sendJobClear()\n{\n    char frame[64];\n    const int payloadLength = snprintf_P(\n        frame, sizeof(frame),\n        PSTR("CMP1|JOB_CANCEL_ACK|0|CANCELLED|ALL_CLEAR|C"));\n    if (payloadLength <= 0 ||\n        static_cast<size_t>(payloadLength) >= sizeof(frame)) return;\n\n    const uint16_t crc = Cmp1Crc::calculate(\n        reinterpret_cast<const uint8_t*>(frame),\n        static_cast<size_t>(payloadLength));\n    const int suffixLength = snprintf_P(\n        frame + payloadLength,\n        sizeof(frame) - static_cast<size_t>(payloadLength),\n        PSTR("|%04X\\n"), static_cast<unsigned int>(crc));\n    if (suffixLength <= 0 ||\n        static_cast<size_t>(suffixLength) >=\n            sizeof(frame) - static_cast<size_t>(payloadLength)) return;\n\n    const size_t frameLength = static_cast<size_t>(payloadLength + suffixLength);\n    m_serial.write(reinterpret_cast<const uint8_t*>(frame), frameLength);\n}\n\nvoid UartEventTransport::writeJobReply(bool cancelReply,\n''')

# Arduino normal JOB_CANCEL becomes idempotent: an already absent old job is a
# successful result, while a different active remote job or any run evidence is
# still rejected.
replace_once(
    "firmware/arduino/src/main.cpp",
    '''void processRemoteCancels()\n{\n    uint32_t jobId = 0UL;\n    while (espTransport.takeRemoteCancel(jobId))\n    {\n        const CM::WindingJob& active = machine.job();\n        const bool canCancel =\n            machine.state() == CM::MachineState::Ready &&\n            active.source == CM::JobSource::Esp32Web &&\n            active.jobId == jobId &&\n            active.currentRunId == 0UL &&\n            active.completedRuns == 0U;\n\n        const bool cancelled = canCancel && machine.cancel();\n        espTransport.sendJobCancelResult(jobId,\n                                         cancelled,\n                                         cancelled ? "CANCELLED" : "BUSY_OR_MISMATCH");\n\n        Serial.print(F("CM_JOB CANCEL id="));\n        Serial.print(jobId);\n        Serial.print(F(" result="));\n        Serial.println(cancelled ? F("CANCELLED") : F("REJECTED"));\n    }\n}\n''',
    '''void processRemoteCancels()\n{\n    uint32_t jobId = 0UL;\n    while (espTransport.takeRemoteCancel(jobId))\n    {\n        const CM::WindingJob& active = machine.job();\n        const bool remotePresent =\n            active.source == CM::JobSource::Esp32Web && active.jobId != 0UL;\n        const bool exactReady =\n            machine.state() == CM::MachineState::Ready &&\n            remotePresent && active.jobId == jobId &&\n            active.currentRunId == 0UL && active.completedRuns == 0U;\n        const bool alreadyClear = !remotePresent;\n\n        bool cancelled = false;\n        const char* detail = "BUSY_OR_MISMATCH";\n        if (exactReady)\n        {\n            cancelled = machine.cancel();\n            detail = cancelled ? "CANCELLED" : "BUSY_OR_MISMATCH";\n        }\n        else if (alreadyClear)\n        {\n            // Idempotent cancellation: ESP32 may be retrying after Arduino\n            // already cleared the job or after a reboot. Do not reject absence.\n            cancelled = true;\n            detail = "ALREADY_CLEAR";\n        }\n\n        espTransport.sendJobCancelResult(jobId, cancelled, detail);\n\n        Serial.print(F("CM_JOB CANCEL id="));\n        Serial.print(jobId);\n        Serial.print(F(" result="));\n        Serial.println(cancelled ? F("CANCELLED") : F("REJECTED"));\n    }\n}\n''')

replace_once(
    "firmware/arduino/src/main.cpp",
    '''bool synchronizationError = false;\nuint32_t lastAliveReportMs = 0UL;\n\nint freeSramBytes()\n''',
    '''bool synchronizationError = false;\nuint32_t lastAliveReportMs = 0UL;\nuint8_t emergencyClearSequenceIndex = 0U;\nuint32_t emergencyClearLastKeyMs = 0UL;\n\nint freeSramBytes()\n''')

replace_once(
    "firmware/arduino/src/main.cpp",
    '''void processKeypad()\n{\n#if CM_FEATURE_KEYPAD_4X4\n    const char key = keypad.getKey();\n    if (key == NO_KEY) return;\n\n    bool handled = false;\n''',
    '''bool processEmergencyJobClearKey(char key)\n{\n    static const char Sequence[] = {'D', '*', '#', 'D'};\n    const uint32_t nowMs = millis();\n\n    const CM::MachineState state = machine.state();\n    if (state == CM::MachineState::Winding ||\n        state == CM::MachineState::Paused ||\n        state == CM::MachineState::ManualRun ||\n        state == CM::MachineState::CoilComplete ||\n        state == CM::MachineState::JobComplete)\n    {\n        emergencyClearSequenceIndex = 0U;\n        return false;\n    }\n\n    if (emergencyClearSequenceIndex != 0U &&\n        static_cast<uint32_t>(nowMs - emergencyClearLastKeyMs) > 4000UL)\n    {\n        emergencyClearSequenceIndex = 0U;\n    }\n\n    if (key != Sequence[emergencyClearSequenceIndex])\n    {\n        emergencyClearSequenceIndex = key == Sequence[0] ? 1U : 0U;\n        emergencyClearLastKeyMs = nowMs;\n        return key == Sequence[0];\n    }\n\n    ++emergencyClearSequenceIndex;\n    emergencyClearLastKeyMs = nowMs;\n    if (emergencyClearSequenceIndex < sizeof(Sequence)) return true;\n    emergencyClearSequenceIndex = 0U;\n\n    const CM::WindingJob& active = machine.job();\n    const bool remotePresent =\n        active.source == CM::JobSource::Esp32Web && active.jobId != 0UL;\n    if (remotePresent)\n    {\n        const bool safeRemoteReady =\n            machine.state() == CM::MachineState::Ready &&\n            active.currentRunId == 0UL && active.completedRuns == 0U;\n        if (!safeRemoteReady || !machine.cancel())\n        {\n            Serial.println(F("CM_JOB EMERGENCY_CLEAR result=REJECTED_ACTIVE_RUN"));\n            return true;\n        }\n    }\n\n    // This frame never means RUN_COMPLETED. It only proves that Arduino holds\n    // no ESP32 remote job, allowing ESP32 to clear pending/accepted no-run state.\n    espTransport.sendJobClear();\n#if CM_FEATURE_BUZZER\n    buzzer.startJobAcceptedSignal(nowMs);\n#endif\n    Serial.println(F("CM_JOB EMERGENCY_CLEAR result=ALL_CLEAR"));\n    return true;\n}\n\nvoid processKeypad()\n{\n#if CM_FEATURE_KEYPAD_4X4\n    const char key = keypad.getKey();\n    if (key == NO_KEY) return;\n    if (processEmergencyJobClearKey(key)) return;\n\n    bool handled = false;\n''')

print("job cancel resilience patch applied")
